const tierConfigs = [
  {
    prefix: "bs",
    name: "Basic Starter",
    description: "Foundation-level strategy participation with conservative risk parameters",
    range: "$10 – $100",
    roi: { min: 1, max: 5 },
    packageStart: 1,
    amounts: [10, 25, 50, 75, 100],
    packageNames: ["Entry Access", "Foundation Access", "Core Access", "Growth Access", "Premium Starter"],
    ranks: ["Rookie", "Novice", "Explorer", "Voyager", "Pioneer"],
  },
  {
    prefix: "pb",
    name: "Pro Builder",
    description: "Professional-grade strategies with advanced AI signal processing",
    range: "$200 – $750",
    roi: { min: 1, max: 10 },
    packageStart: 6,
    amounts: [200, 300, 400, 500, 750],
    packageNames: ["Pro Foundation", "Pro Advanced", "Pro Elite", "Pro Strategic", "Pro Maximum"],
    ranks: ["Builder", "Strategist", "Innovator", "Achiever", "Visionary"],
  },
  {
    prefix: "ei",
    name: "Elite Investor",
    description: "Institutional AI models with sophisticated market analysis",
    range: "$1,000 – $5,000",
    roi: { min: 1, max: 15 },
    packageStart: 11,
    amounts: [1000, 1500, 2000, 3000, 5000],
    packageNames: ["Elite Foundation", "Elite Enhanced", "Elite Premium", "Elite Strategic", "Elite Maximum"],
    ranks: ["Elite", "Master", "Champion", "Hero", "Legend"],
  },
  {
    prefix: "md",
    name: "Master Director",
    description: "Enterprise-level deployment with systematic alpha extraction",
    range: "$7,500 – $25,000",
    roi: { min: 1, max: 20 },
    packageStart: 16,
    amounts: [7500, 10000, 15000, 20000, 25000],
    packageNames: ["Master Foundation", "Master Enhanced", "Master Premium", "Master Strategic", "Master Maximum"],
    ranks: ["Director", "Executive", "Guardian", "Commander", "Sentinel"],
  },
  {
    prefix: "ga",
    name: "Global Ambassador",
    description: "Proprietary institutional infrastructure with custom strategy development",
    range: "$35,000 – $100,000",
    roi: { min: 1, max: 25 },
    packageStart: 21,
    amounts: [35000, 50000, 65000, 80000, 100000],
    packageNames: ["Ambassador Foundation", "Ambassador Enhanced", "Ambassador Premium", "Ambassador Strategic", "Ambassador Maximum"],
    ranks: ["Ambassador", "Global", "Platinum", "Diamond", "Pinnacle"],
  },
];

export const packages = tierConfigs.flatMap((tier) =>
  tier.amounts.map((amount, index) => ({
    id: `${tier.prefix}-${index + 1}`,
    tier: tier.name,
    name: tier.packageNames[index],
    rank: tier.ranks[index],
    amount,
    roi: {
      min: tier.roi.min,
      max: tier.roi.max,
    },
    description: `${tier.name} package — ${tier.description}.`,
  })),
);

export const tierGroups = tierConfigs.map((tier) => ({
  name: tier.name,
  range: tier.range,
  roiText: `${tier.roi.min}% to ${tier.roi.max}%`,
  description: tier.description,
  packages: packages.filter((pkg) => pkg.tier === tier.name),
}));
